# 1
Write a Python Program to Add Two Matrices?

In [12]:
import numpy as np
mat1 = np.matrix([[1, 2], [3, 4],[5,6]])
mat2 = np.matrix([[7,8],[9,10],[11,12]])
print(f"{mat1} \n")
print(f"{mat2} \n")
sum_matrix = np.matrix([[0,0],[0,0],[0,0]])
#
# iterate through rows  
for i in range(len(mat1)):  
   # iterate through columns  
   for j in range(len(mat1[0])):  
        sum_matrix[i][j] = mat1[i][j] + mat2[i][j] 
#
print(f"{sum_matrix} \n")

[[1 2]
 [3 4]
 [5 6]] 

[[ 7  8]
 [ 9 10]
 [11 12]] 

[[ 8 10]
 [12 14]
 [16 18]] 



# 2
Write a Python Program to Multiply Two Matric

In [12]:
# BY BASIC METHOD i.e. for loop
# FOR MULTIPLICATION THE NUMBER OF COLUMNS IN FIRST MATRIX AND NO OF ROWS
# IN SECOND MATRIX MUST BE EQUAL. i.e. IF FIRST MATRIX IS m*n THEN
# SECOND MATRIX IS n*p. AND RESULT OF MULTIPLICATION IS m*p 
# 3x3 matrix
X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]
# 3x4 matrix
Y = [[5,8,1,2],
    [6,7,3,0],
    [4,5,9,1]]
# result is 3x4
result = [[0,0,0,0],
         [0,0,0,0],
         [0,0,0,0]]
# iterate through rows of X
for i in range(len(mat1)):
   # iterate through columns of Y
   for j in range(len(mat2[0])):
       # iterate through rows of Y
       for k in range(len(mat2)):
            result[i][j] =  result[i][j] + mat1[i][k] * mat2[k][j]
            
for r in result:
    print(r)

[114, 160, 60, 27]
[74, 97, 73, 14]
[119, 157, 112, 23]


In [11]:
# BY numpy using np.dot
import numpy as np
# 3x3 matrix
X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]
# 3x4 matrix
Y = [[5,8,1,2],
    [6,7,3,0],
    [4,5,9,1]]
np.dot(X,Y)

array([[114, 160,  60,  27],
       [ 74,  97,  73,  14],
       [119, 157, 112,  23]])

In [4]:
# By tensorflow matmul module
import tensorflow as tf
import numpy as np
# 3x3 matrix
X = [12,7,3],[4,5,6],[7,8,9]
# 3x4 matrix
Y = [5,8,1,2],[6,7,3,0],[4,5,9,1]
tf.matmul(X,Y)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[114, 160,  60,  27],
       [ 74,  97,  73,  14],
       [119, 157, 112,  23]])>

# 3
Write a Python Program to Transpose a Matrix?

In [13]:
# Program to transpose a matrix using a nested loop
# Making rows of a matrix to columns and columns to rows gives transpose
# So transpose of a m* n matrix will be a n*m matrix
mat = [[12,7],
    [4 ,5],
    [3 ,8]]
transpose_mat = [[0,0,0],[0,0,0]]
       
# iterate through rows
for i in range(len(mat)):
   # iterate through columns
   for j in range(len(mat[0])):
        transpose_mat[j][i] = mat[i][j]

for row in transpose_mat:
    print(row)

[12, 4, 3]
[7, 5, 8]


In [ ]:
#transpose a matrix using list comprehension
mat1 = [[12,7],[4 ,5],[3 ,8]]    
   
result = [[mat1[j][i] for j in range(len(mat1))] for i in range(len(mat1[0]))]

for r in result:
    print(r)

In [14]:
# using numpy aray.transpose() function
import numpy as np

arr1 = np.array([[1, 2, 3], [4, 5, 6]])

print(f'Original Array:\n{arr1}')

arr1_transpose = arr1.transpose()

print(f'Transposed Array:\n{arr1_transpose}')

Original Array:
[[1 2 3]
 [4 5 6]]
Transposed Array:
[[1 4]
 [2 5]
 [3 6]]


# 4
Write a Python Program to Sort Words in Alphabetic Order?

In [4]:
# let us begin with a sentence
my_string = "Hello i am considering this string as an example of array of words"
# Convert all characters to lower and store them in a list
word_array = [word.lower() for word in my_string.split()]
# sort the list
word_array.sort()
# Disply result
for word in word_array:
    print(word)
# Output in the form of sorted words
print(list(word_array))


am
an
array
as
considering
example
hello
i
of
of
string
this
words
['am', 'an', 'array', 'as', 'considering', 'example', 'hello', 'i', 'of', 'of', 'string', 'this', 'words']


# 5
Write a Python Program to Remove Punctuation From a String?

In [22]:
# By using regex
import re
my_string = "Hello! How are you? Earned some $$? I am fine @myhome on #twitter"
print(f"Original string is \n{my_string}")
new_str = re.sub(r'[^\w\s]','',my_string)
print (f"The string without punctuation is \n{new_str}")

Original string is 
Hello! How are you? Earned some $$? I am fine @myhome on #twitter
The string without punctuation is 
Hello How are you Earned some  I am fine myhome on twitter


In [21]:
# By uisng for loop and a collection of all punctuations
my_string = "Hello! How are you? Earned some $$? I am fine @myhome on #twitter"
print(f"Original string is \n{my_string}")
punctuations ='''!()-[]{};:'"\,<>./?@#$%^&*_~'''
def remove_punctuations(my_string):
    for letter in my_string.lower():
        if letter in punctuations:
            my_string = my_string.replace(letter,"")
    return my_string
# print result
print(f"After removing punctuations the string is \n{remove_punctuations(my_string)}")

Original string is 
Hello! How are you? Earned some $$? I am fine @myhome on #twitter
After removing punctuations the string is 
Hello How are you Earned some  I am fine myhome on twitter


In [24]:
# By using string.translate(). 
import string
s = "string.?# With. $ @ { } Punctuation?"
s.translate(str.maketrans('', '', string.punctuation))

'string With     Punctuation'